### PR TITLE
Ignore source maps in boot

### PR DESCRIPTION
**Pull request by zbarbuto**
### Description

Same as #263 but fix for 3.x version

#### Related issues

- #255

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

cc @bajtos

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
Let's wait until #263 is landed and then forward-port the final result.

**Comment by zbarbuto** [comment]
Done deal

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
Landed, thank you for the contribution!

**Pull request merged**
