### PR TITLE
[BUG] Middleware is loading .js.map of .js

### PR DESCRIPTION
**Pull request by ivanproskuryakov**
https://github.com/strongloop/loopback-boot/issues/255

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by zbarbuto** [comment]
@ivanproskuryakov Any chance you could fix the build issues? Would love to use this fix myself.

**Comment by ivanproskuryakov** [comment]
Hi @zbarbuto, there was a problem with title length thrown by "Commit Linter".
It was adjusted the same day, but I don't know how to rerun the Checks.

**Comment by zbarbuto** [comment]
Fair enough. I noticed anyway there was an existing pull 245 to fix the issue which has a bunch of discussion on it. Have switched to using a fork until either gets merged. Thanks.

**Comment by ivanproskuryakov** [comment]
@zbarbuto Hey Zak, shall we merge it?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by zbarbuto** [comment]
@ivanproskuryakov Not really my call to make as it's not my repo. But see discussion in #245 as to why it may not have been merged already.

**Comment by ivanproskuryakov** [comment]
@zbarbuto sure, I've seen it. Since it's duplicated, I can close this PR and issue.

**Comment by bajtos** [comment]
Closing as a duplicate of #264.

**Pull request closed without merging**
