### PR TITLE
Change test cases port to be dynamic

### PR DESCRIPTION
**Pull request by davidcheung**
connect to strongloop/loopback-boot#197

### CODE REVIEW

**Comment by davidcheung** [comment]
@slnode test please

**Comment by davidcheung** [comment]
@slnode test please

**Comment by davidcheung** [comment]
@gunjpan PTAL

**Comment by gunjpan** [comment]
@davidcheung : Does that pass on local? changes seems trivial to me.

**Comment by davidcheung** [comment]
@gunjpan yes it passes on local

**Pull request merged**
