### PR TITLE
Add support for async component initialization

### PR DESCRIPTION
**Pull request by mdh-cc**
#### Related issues

- #258

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
@raymondfeng could you PTAL? I think async component should support promise/async-await style too, but starting will callback support is a good first step that can be landed on its own IMO.

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
In October 2018, LoopBack 4.0 GA was released. LoopBack 3 and its supporting modules have entered LTS mode. Per our [Long Term Support Policy](https://loopback.io/doc/en/contrib/Long-term-support.html), this means new features are no longer accepted.

I am closing this pull request as rejected. I sincerely apologize that we were not able to review and accept these changes in time 😢

**Pull request closed without merging**
