### PR TITLE
feat(compiler) Make recursive dir reader.

### PR DESCRIPTION
**Pull request by stanislavt**
I've added an ability to read all boot scripts recursively.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by superkhau** [comment]
Can you add some tests to verify your changes and prevent regressions in the future?

**Comment by stanislavT** [comment]
@superkhau , Yes, sure!

**Comment by bajtos** [comment]
I am closing this patch as abandoned. @stanislavt feel free to reopen when/if you get a chance to add the tests as asked by @superkhau's comment above.

**Pull request closed without merging**
