### PR TITLE
Fix lodash 4.0.0 breaking changes

### PR DESCRIPTION
**Pull request by jdrouet**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by superkhau** [comment]
@slnode test please

**Comment by jdrouet** [comment]
@superkhau _.unique was an alias to _.uniq

**Comment by superkhau** [comment]
> _.unique was an alias to _.uniq

Makes sense. LGTM and thanks for the contribution. ;)

**Pull request merged**
