### PR TITLE
Environment-specific loading for 'model-config'

### PR DESCRIPTION
**Pull request by dashby3000**
Added code to allow model-config to respect model-config.local.js and model-config.env.js as do other config files.

### CODE REVIEW

**Comment by raymondfeng** [comment]
Good idea

**Comment by raymondfeng** [comment]
@dashby3000 There is a style issue that fails the build.
```
Missing space after line comment at ./lib/config-loader.js :
    33 |ConfigLoader.loadModels = function(rootDir, env) {
    34 |  /*jshint unused:false */
    35 |  //return tryReadJsonConfig(rootDir, 'model-config') || {};
----------^
    36 |  return loadNamed(rootDir, env, 'model-config', mergeModelConfig);
    37 |};
```
Can you fix it? 

A test is also appreciated to cover your enhancement.

**Comment by dashby3000** [comment]
Updated to fix the styling issue.  As for the test, I will just duplicate the tests that already exits for checking the merge.

**Comment by raymondfeng** [comment]
Closed by https://github.com/strongloop/loopback-boot/pull/143

**Pull request closed without merging**
