### PR TITLE
config: support load via .js

### PR DESCRIPTION
**Pull request by yorkie**
as title

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by raymondfeng** [comment]
Which json files do you want to allow js? A lot of them already supports it, for example, server/datasources.local.js for server/datasources.json.

**Comment by yorkie** [comment]
Hey Feng, my use case is I wanna config some of fields in datasources in env-specific way, so actually I just want the default config looks like:

```js
module.exports = {
  mongo: {
    url: process.env.MONGO_URI
  }
};
```

The loopback config doesn't support the JavaScript(.js) file for the default config, this is what I need.

**Comment by yorkie** [comment]
Without this, I need write duplicated and redundant config for this mongoDB, I just think that is great if loopback can load `server/datasources.js`.

**Comment by raymondfeng** [comment]
You should be able to do that with `server/datasources.local.js` today.

**Comment by yorkie** [comment]
If I specify `NODE_ENV=prod node server/app.js`, local is able to be loaded as well? I can't see something about local from your search algorithm actually.

**Comment by raymondfeng** [comment]
datasources.local.js is loaded under all envs.

**Comment by raymondfeng** [comment]
See http://docs.strongloop.com/display/LB/datasources.json#datasources.json-Environment-specificconfiguration

**Comment by yorkie** [comment]
Thanks I see, I will close this :)

**Pull request closed without merging**
