### PR TITLE
Use polyfill code for Number.isFinite

### PR DESCRIPTION
**Pull request by mrfelton**
Fix for #123

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@mrfelton thank you for the pull request. I am afraid it is a breaking change. Before we made modifications to this part, loopback-boot was accepting any value that could be parsed as an integer, e.g "10abc". (Unfortunately this was not covered by tests.)

Can you please rework the patch to honour this behaviour and also add a unit-test to make sure this behaviour is covered by our test suite?

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
@mrfelton I also need you to sign our CLA before I can land your patch, see the failed "clahub" check.

**Comment by bajtos** [comment]
Closing in favour or https://github.com/strongloop/loopback-boot/pull/126.

FWIW, the claim *loopback-boot was accepting any value that could be parsed as an integer, e.g "10abc"* was actually wrong.

**Pull request closed without merging**
