### PR TITLE
Add support for ES6 style async boot scripts

### PR DESCRIPTION
**Pull request by lehni**
### Description

This PR allows boot scripts to be defined in the ES6 async fashion, without the need for passing callbacks:

```js
module.exports = async function(app) {
   ...
};
```

#### Related issues

- None

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@raymondfeng @davidcheung please review. You may want to consider my comments in https://github.com/strongloop/loopback-boot/pull/252 too.

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
Hi @lehni, could you please forward-port the changes from #252 that you made as part of the review process?

**Comment by lehni** [comment]
@bajtos I am back from my holiday, will look into these pending things now!

**Comment by bajtos** [comment]
@lehni sounds good, welcome back! :)

**Comment by lehni** [comment]
@bajtos this PR now contains the changes of both #252 and #260 for the master branch.

**Pull request merged**
